name: Feature Request
description: I won't add winning icons, so don't ask for that. REQUESTING FOR A STAGE EDITOR WILL RESULT IN A BAN, SHADOWMARIO WILL DO IT LATER GOD DAMMIT.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on this engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - Winning Icons and Stage Editor
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
